services:
  app:
    build: .
    volumes:
      - ./:/app
    ports:
      - 8080:8080
  
  db:
    image: postgres:latest
    volumes:
      - gin_db:/var/lib/postgresql
      - ../00_db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: "crud_user"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "crud"

volumes:
  gin_db: